import type { Supplier } from '@/types/supplier';

export const SUPPLIERS: Supplier[] = [
  {
    slug: 'prairie-moon',
    name: 'Prairie Moon Nursery',
    url: 'https://www.prairiemoon.com',
    location: 'Winona, MN',
    description: 'Largest selection of native seeds and plants for the upper Midwest. Ships nationwide. Excellent online catalog with growing info.',
    shipping: true,
    pickup: false,
    specialties: ['seed', 'plug', 'bare_root'],
    phone: '(507) 452-1362',
  },
  {
    slug: 'pizzo',
    name: 'Pizzo Native Plant Nursery',
    url: 'https://www.pizzonursery.com',
    location: 'Leland, IL',
    description: '40-acre facility growing plants from locally collected seed. Strong focus on ecological restoration. Serves Chicagoland area.',
    shipping: false,
    pickup: true,
    specialties: ['plug', 'potted'],
    phone: '(815) 981-8000',
  },
  {
    slug: 'possibility-place',
    name: 'Possibility Place Nursery',
    url: 'https://www.possibilityplace.com',
    location: 'Monee, IL',
    description: 'Over 300 species of NE Illinois native perennials, trees, and shrubs. Operating since 1983. Retail open April-November.',
    shipping: true,
    pickup: true,
    specialties: ['potted', 'bare_root'],
    phone: '(708) 534-3988',
  },
  {
    slug: 'the-growing-place',
    name: 'The Growing Place',
    url: 'https://www.thegrowingplace.com',
    location: 'Aurora & Naperville, IL',
    description: 'Two locations in the western suburbs. General nursery with a solid native plant selection. Knowledgeable staff.',
    shipping: false,
    pickup: true,
    specialties: ['potted'],
    phone: '(630) 355-4000',
  },
  {
    slug: 'red-buffalo',
    name: 'Red Buffalo Nursery',
    url: '',
    location: 'Richmond, IL',
    description: 'Northern Illinois native plant nursery specializing in prairie and woodland species. Seeds and plants available.',
    shipping: false,
    pickup: true,
    specialties: ['seed', 'plug', 'potted'],
    phone: '(815) 648-4848',
  },
  {
    slug: 'living-habitats',
    name: 'Living Habitats',
    url: 'https://www.livinghabitats.com',
    location: 'Chicago, IL',
    description: 'Urban-focused native plant supplier in the city. Good selection for small urban gardens and container planting.',
    shipping: false,
    pickup: true,
    specialties: ['potted', 'plug'],
    phone: '(773) 467-1634',
  },
  {
    slug: 'red-stem',
    name: 'Red Stem Native Landscapes',
    url: 'https://www.redstemnativelandscapes.com',
    location: 'Chicago, IL',
    description: 'Native landscape design and plant supply in Chicago. Offers consultation services alongside plant sales.',
    shipping: false,
    pickup: true,
    specialties: ['potted', 'plug'],
    phone: '(773) 454-4800',
  },
];

export function getSupplierBySlug(slug: string): Supplier | undefined {
  return SUPPLIERS.find(s => s.slug === slug);
}
