'use client';

import { useState, useRef, useCallback } from 'react';
import SunCalc from 'suncalc';
import type { PlanPlant, ExclusionZone, ExistingTree } from '@/types/plan';

export interface NearbyBuilding {
  lat: number;
  lng: number;
  heightMeters: number;
  widthMeters?: number;
}

export type EditTool = 'select' | 'path' | 'tree';

/** Visual style used to render plants in the export.
 *  - 'dots': numbered circles, sized to plant spread (the historical look).
 *  - 'matrix': filled grid squares, one per placement, with species code label
 *    — best for installation crews working with a tape measure.
 *  - 'tapestry': Voronoi cell polygons (from PlanPlant.cellGeoJson) in the
 *    Oudolf palette — falls back to dots when the plan was generated by a
 *    layout that doesn't ship cells. */
export type PlanRenderStyle = 'dots' | 'matrix' | 'tapestry';

interface GridPlanViewProps {
  widthFt: number;
  heightFt: number;
  centerLat: number;
  centerLng: number;
  plants: PlanPlant[];
  exclusionZones?: ExclusionZone[];
  existingTrees?: ExistingTree[];
  selectedSlug?: string | null;
  onPlantClick?: (slug: string) => void;
  nearbyBuildings?: NearbyBuilding[];
  showSatellite?: boolean;
  showShadows?: boolean;
  shadowHour?: number; // 0–24
  /** Visual style for plant placements. Default 'dots' preserves the legacy
   *  numbered-circle look used by every existing print page. */
  renderStyle?: PlanRenderStyle;
  // Editing props
  editable?: boolean;
  editTool?: EditTool;
  editTreeSize?: number;
  onPathDrawn?: (zone: ExclusionZone) => void;
  onTreePlaced?: (tree: ExistingTree) => void;
  onFeatureRemoved?: (type: 'zone' | 'tree', id: string) => void;
}

// Tapestry palette + helpers — mirrors MapboxMap.tsx so the print/export view
// matches the on-screen Voronoi tapestry the user sees in the planner.
const TAPESTRY_PALETTE = [
  '#c9d13a', '#f6c845', '#ea5e52', '#9b4a92', '#74b340',
  '#ee7a70', '#d6934c', '#c16a9a', '#e7a2bd', '#7f6ba2',
  '#cfd56f', '#f8a94c', '#6bbeb8', '#b56363', '#d8d080',
  '#83a66e', '#e5ca4a', '#d27c48', '#89b995', '#bc8ab8',
];

function hashSlug(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h * 16777619) >>> 0;
  }
  return h;
}

function tapestryColor(speciesIdx: number, slug: string): string {
  const idx = (speciesIdx + hashSlug(slug || '')) % TAPESTRY_PALETTE.length;
  return TAPESTRY_PALETTE[idx];
}

function speciesAbbrev(slug: string | undefined, name: string): string {
  const first = (slug || '').split('-')[0];
  if (first && first.length >= 3) return first.slice(0, 3).toUpperCase();
  const words = (name || '').trim().split(/\s+/);
  if (words.length >= 2) return (words[0][0] + words[1][0]).toUpperCase();
  return (name || '').slice(0, 3).toUpperCase();
}

const PX_PER_FT = 22;
const GRID_SPACING_FT = 2;

function getPlantColor(bloomColor: string): string {
  const colors: Record<string, string> = {
    purple: '#7c3aed', blue: '#2563eb', pink: '#db2777', red: '#dc2626',
    orange: '#ea580c', yellow: '#ca8a04', white: '#94a3b8', green: '#16a34a',
    lavender: '#8b5cf6', gold: '#b45309', crimson: '#b91c1c', coral: '#e05d44',
    violet: '#6d28d9', magenta: '#c026d3', cream: '#b45309', rose: '#e11d48',
    bronze: '#78350f', silver: '#64748b', rust: '#92400e', scarlet: '#991b1b',
    tan: '#7c6144', brown: '#6b3a2a',
  };
  return colors[bloomColor?.toLowerCase()] || '#6b7280';
}

function formatHour(h: number): string {
  const hour = Math.floor(h);
  const min = Math.round((h % 1) * 60);
  const ampm = hour >= 12 ? 'PM' : 'AM';
  const h12 = hour === 0 ? 12 : hour > 12 ? hour - 12 : hour;
  return `${h12}:${min.toString().padStart(2, '0')} ${ampm}`;
}

/** Convert compass bearing (0=N, 90=E) to SVG x,y on a circle */
function bearingToXY(bearingDeg: number, radius: number) {
  const rad = bearingDeg * Math.PI / 180;
  return { x: Math.sin(rad) * radius, y: -Math.cos(rad) * radius };
}

export default function GridPlanView({
  widthFt, heightFt, centerLat, centerLng,
  plants, exclusionZones = [], existingTrees = [],
  selectedSlug, onPlantClick,
  nearbyBuildings = [],
  showSatellite,
  showShadows,
  shadowHour = 14,
  renderStyle = 'dots',
  editable, editTool = 'select', editTreeSize = 20,
  onPathDrawn, onTreePlaced, onFeatureRemoved,
}: GridPlanViewProps) {
  const shadowsOn = showShadows !== undefined ? showShadows : nearbyBuildings.length > 0;
  const svgRef = useRef<SVGSVGElement>(null);
  const [drawing, setDrawing] = useState(false);
  const [drawStart, setDrawStart] = useState<{ x: number; y: number } | null>(null);
  const [drawCurrent, setDrawCurrent] = useState<{ x: number; y: number } | null>(null);
  const [pendingPath, setPendingPath] = useState<{ x: number; y: number; w: number; h: number } | null>(null);
  const [pathLabel, setPathLabel] = useState('');
  const [popupPlant, setPopupPlant] = useState<{ plant: PlanPlant; cx: number; cy: number } | null>(null);

  // Add padding around the garden so surrounding context is visible
  const PAD_FT = 4;
  const svgWidth = (widthFt + PAD_FT * 2) * PX_PER_FT;
  const svgHeight = (heightFt + PAD_FT * 2) * PX_PER_FT;
  const padPx = PAD_FT * PX_PER_FT;
  /** Convert a position (ft from garden origin) to SVG px, offset by padding */
  const ftToPx = (ft: number) => ft * PX_PER_FT + padPx;
  /** Convert a dimension (ft) to SVG px, no offset */
  const ftToSize = (ft: number) => ft * PX_PER_FT;

  // Bounding box from garden dimensions — always use center + size for correct scale
  const plantsWithCoords = plants.filter(p => p.lat && p.lng);
  const metersPerFt = 0.3048;
  const latPerFt = metersPerFt / 111320;
  const lngPerFt = metersPerFt / (111320 * Math.cos(centerLat * Math.PI / 180));
  const minLat = centerLat - (heightFt / 2) * latPerFt;
  const maxLat = centerLat + (heightFt / 2) * latPerFt;
  const minLng = centerLng - (widthFt / 2) * lngPerFt;
  const maxLng = centerLng + (widthFt / 2) * lngPerFt;

  function latLngToFt(lat: number, lng: number): { xFt: number; yFt: number } {
    const latRange = maxLat - minLat || 0.0001;
    const lngRange = maxLng - minLng || 0.0001;
    return {
      xFt: ((lng - minLng) / lngRange) * widthFt,
      yFt: ((maxLat - lat) / latRange) * heightFt,
    };
  }

  // ── Inverse coordinate conversion (SVG pixels → lat/lng) ────────────────────
  const ftToLatLng = useCallback((xFt: number, yFt: number) => {
    const latRange = maxLat - minLat || 0.0001;
    const lngRange = maxLng - minLng || 0.0001;
    return {
      lat: maxLat - (yFt / heightFt) * latRange,
      lng: minLng + (xFt / widthFt) * lngRange,
    };
  }, [minLat, maxLat, minLng, maxLng, widthFt, heightFt]);

  function getSVGPoint(e: React.MouseEvent<SVGSVGElement>): { x: number; y: number } {
    const svg = svgRef.current!;
    const rect = svg.getBoundingClientRect();
    return {
      x: ((e.clientX - rect.left) / rect.width) * svgWidth,
      y: ((e.clientY - rect.top) / rect.height) * svgHeight,
    };
  }

  function handleMouseDown(e: React.MouseEvent<SVGSVGElement>) {
    if (!editable) return;
    if (editTool === 'path') {
      const pt = getSVGPoint(e);
      const snap = ftToPx(GRID_SPACING_FT);
      const snappedX = Math.round(pt.x / snap) * snap;
      const snappedY = Math.round(pt.y / snap) * snap;
      setDrawStart({ x: snappedX, y: snappedY });
      setDrawCurrent({ x: snappedX, y: snappedY });
      setDrawing(true);
    } else if (editTool === 'tree') {
      const pt = getSVGPoint(e);
      const xFt = pt.x / PX_PER_FT;
      const yFt = pt.y / PX_PER_FT;
      const { lat, lng } = ftToLatLng(xFt, yFt);
      const newTree: ExistingTree = {
        id: `tree-${Date.now()}`,
        lat, lng,
        canopyDiameterFt: editTreeSize,
        label: 'Existing Tree',
      };
      (newTree as any).gridXFt = xFt;
      (newTree as any).gridYFt = yFt;
      onTreePlaced?.(newTree);
    }
  }

  function handleMouseMove(e: React.MouseEvent<SVGSVGElement>) {
    if (!editable || !drawing || editTool !== 'path') return;
    const pt = getSVGPoint(e);
    const snap = ftToPx(GRID_SPACING_FT);
    setDrawCurrent({ x: Math.round(pt.x / snap) * snap, y: Math.round(pt.y / snap) * snap });
  }

  function handleMouseUp() {
    if (!editable || !drawing || !drawStart || !drawCurrent || editTool !== 'path') return;
    const x = Math.min(drawStart.x, drawCurrent.x);
    const y = Math.min(drawStart.y, drawCurrent.y);
    const w = Math.abs(drawCurrent.x - drawStart.x);
    const h = Math.abs(drawCurrent.y - drawStart.y);
    if (w > ftToPx(1) && h > ftToPx(1)) {
      setPendingPath({ x, y, w, h });
      setPathLabel('');
    }
    setDrawing(false);
    setDrawStart(null);
    setDrawCurrent(null);
  }

  function confirmPath() {
    if (!pendingPath) return;
    const xFt = pendingPath.x / PX_PER_FT;
    const yFt = pendingPath.y / PX_PER_FT;
    const wFt = pendingPath.w / PX_PER_FT;
    const hFt = pendingPath.h / PX_PER_FT;
    const tl = ftToLatLng(xFt, yFt);
    const tr = ftToLatLng(xFt + wFt, yFt);
    const br = ftToLatLng(xFt + wFt, yFt + hFt);
    const bl = ftToLatLng(xFt, yFt + hFt);
    const zone: ExclusionZone = {
      id: `excl-${Date.now()}`,
      geoJson: {
        type: 'Polygon',
        coordinates: [[[tl.lng, tl.lat], [tr.lng, tr.lat], [br.lng, br.lat], [bl.lng, bl.lat], [tl.lng, tl.lat]]],
      },
      label: pathLabel || 'Path',
      type: 'walkway',
    };
    (zone as any).gridRect = { xFt, yFt, wFt, hFt };
    onPathDrawn?.(zone);
    setPendingPath(null);
    setPathLabel('');
  }

  // ── Satellite background URL ────────────────────────────────────────────────
  // Use center/zoom format at zoom 22 (max) and compute exact pixel dimensions
  // so the satellite image matches the grid scale 1:1. Include padding area.
  const MAPBOX_TOKEN = process.env.NEXT_PUBLIC_MAPBOX_TOKEN;
  const MAX_ZOOM = 22;
  const groundResM = (40075016.686 * Math.cos(centerLat * Math.PI / 180)) / (Math.pow(2, MAX_ZOOM) * 256);
  // Pixels needed for the garden + padding at zoom 22
  const totalWidthFt = widthFt + PAD_FT * 2;
  const totalHeightFt = heightFt + PAD_FT * 2;
  const gardenPxW = Math.round((totalWidthFt * metersPerFt) / groundResM);
  const gardenPxH = Math.round((totalHeightFt * metersPerFt) / groundResM);
  // Clamp to Mapbox limits (1–1280), use @2x for retina sharpness
  const satImgW = Math.max(1, Math.min(1280, gardenPxW));
  const satImgH = Math.max(1, Math.min(1280, gardenPxH));
  const satelliteUrl = showSatellite && MAPBOX_TOKEN
    ? `https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v12/static/${centerLng},${centerLat},${MAX_ZOOM},0/${satImgW}x${satImgH}@2x?access_token=${MAPBOX_TOKEN}`
    : null;

  // ── Sun position and path ───────────────────────────────────────────────────
  // Use UTC dates based on garden longitude to avoid timezone issues
  // Local noon ≈ 12:00 - (longitude / 15) UTC
  const year = new Date().getFullYear();
  const localNoonUTC = 12 - (centerLng / 15); // e.g., ~17.8 UTC for Chicago
  const utcShadowHour = shadowHour + (localNoonUTC - 12); // shift by difference from local noon
  const sunDate = new Date(Date.UTC(year, 5, 21, Math.floor(utcShadowHour), Math.round(((utcShadowHour % 1 + 1) % 1) * 60)));
  const sunPos = SunCalc.getPosition(sunDate, centerLat, centerLng);
  const sunAltDeg = sunPos.altitude * 180 / Math.PI;
  const sunAzDeg = (sunPos.azimuth * 180 / Math.PI + 180) % 360;

  // Hourly sun positions for the path arc (in local time at the garden)
  const sunPathPoints: { hour: number; azDeg: number; altDeg: number }[] = [];
  for (let localH = 5; localH <= 21; localH += 0.5) {
    const utcH = localH + (localNoonUTC - 12);
    const d = new Date(Date.UTC(year, 5, 21, Math.floor(utcH), Math.round(((utcH % 1 + 1) % 1) * 60)));
    const p = SunCalc.getPosition(d, centerLat, centerLng);
    const alt = p.altitude * 180 / Math.PI;
    if (alt > 0) sunPathPoints.push({ hour: localH, azDeg: (p.azimuth * 180 / Math.PI + 180) % 360, altDeg: alt });
  }

  // ── Building positions in plan coordinates ──────────────────────────────────
  const buildingInfo = nearbyBuildings.map(b => {
    const { xFt, yFt } = latLngToFt(b.lat, b.lng);
    const wFt = (b.widthMeters ?? 15) * 3.28084;
    const inView = xFt >= -wFt && xFt <= widthFt + wFt && yFt >= -wFt && yFt <= heightFt + wFt;
    const angle = Math.atan2(yFt - heightFt / 2, xFt - widthFt / 2);
    return { ...b, xFt, yFt, wFt, inView, angle };
  });

  // ── Shadow polygons ─────────────────────────────────────────────────────────
  const shadowPolygons: string[] = [];
  if (shadowsOn && (nearbyBuildings.length > 0 || existingTrees.length > 0)) {
    if (sunAltDeg > 2) {
      const altRad = sunAltDeg * Math.PI / 180;
      const shadowDirRad = ((sunAzDeg + 180) % 360) * Math.PI / 180;
      const perpRad = shadowDirRad + Math.PI / 2;
      const M_TO_LAT = 1 / 111320;
      const M_TO_LNG = 1 / (111320 * Math.cos(centerLat * Math.PI / 180));

      const makeShadowPoints = (lat: number, lng: number, heightM: number, widthM: number) => {
        if (heightM <= 0) return null;
        const lenM = Math.min(heightM / Math.tan(altRad), 150);
        const hw = widthM / 2;
        const c = [
          { lat: lat + Math.cos(perpRad) * hw * M_TO_LAT, lng: lng + Math.sin(perpRad) * hw * M_TO_LNG },
          { lat: lat - Math.cos(perpRad) * hw * M_TO_LAT, lng: lng - Math.sin(perpRad) * hw * M_TO_LNG },
          { lat: lat - Math.cos(perpRad) * hw * M_TO_LAT + Math.cos(shadowDirRad) * lenM * M_TO_LAT,
            lng: lng - Math.sin(perpRad) * hw * M_TO_LNG + Math.sin(shadowDirRad) * lenM * M_TO_LNG },
          { lat: lat + Math.cos(perpRad) * hw * M_TO_LAT + Math.cos(shadowDirRad) * lenM * M_TO_LAT,
            lng: lng + Math.sin(perpRad) * hw * M_TO_LNG + Math.sin(shadowDirRad) * lenM * M_TO_LNG },
        ];
        return c.map(p => { const { xFt, yFt } = latLngToFt(p.lat, p.lng); return `${ftToPx(xFt).toFixed(1)},${ftToPx(yFt).toFixed(1)}`; }).join(' ');
      };

      for (const b of nearbyBuildings) {
        const pts = makeShadowPoints(b.lat, b.lng, b.heightMeters, b.widthMeters ?? 15);
        if (pts) shadowPolygons.push(pts);
      }
      for (const t of existingTrees) {
        const pts = makeShadowPoints(t.lat, t.lng, t.canopyDiameterFt * 1.5 * 0.3048, t.canopyDiameterFt * 0.3048);
        if (pts) shadowPolygons.push(pts);
      }
    }
  }

  // ── Species zone backgrounds ────────────────────────────────────────────────
  const speciesGroups = new Map<string, { cx: number; cy: number; r: number; color: string }>();
  const slugPositions = new Map<string, { xFt: number; yFt: number; color: string }[]>();
  for (const p of plantsWithCoords) {
    const { xFt, yFt } = latLngToFt(p.lat!, p.lng!);
    if (xFt < 0 || xFt > widthFt || yFt < 0 || yFt > heightFt) continue;
    if (!slugPositions.has(p.plantSlug)) slugPositions.set(p.plantSlug, []);
    slugPositions.get(p.plantSlug)!.push({ xFt, yFt, color: getPlantColor(p.bloomColor) });
  }
  for (const [, pts] of slugPositions) {
    const cx = pts.reduce((s, p) => s + p.xFt, 0) / pts.length;
    const cy = pts.reduce((s, p) => s + p.yFt, 0) / pts.length;
    const r = Math.max(...pts.map(p => Math.sqrt((p.xFt - cx) ** 2 + (p.yFt - cy) ** 2))) + 1.5;
    speciesGroups.set(`${cx}-${cy}`, { cx, cy, r, color: pts[0].color });
  }

  // ── Grid lines (style adapts to satellite background) ──────────────────────
  const isSat = !!showSatellite;
  const gridLines: React.ReactElement[] = [];
  for (let x = 0; x <= widthFt; x += GRID_SPACING_FT) {
    const major = x % 10 === 0;
    gridLines.push(
      <line key={`v${x}`} x1={ftToPx(x)} y1={0} x2={ftToPx(x)} y2={svgHeight}
        stroke={isSat ? 'rgba(255,255,255,0.25)' : '#d1d5db'}
        strokeWidth={major ? 1 : 0.4}
        strokeOpacity={isSat ? (major ? 0.5 : 0.25) : 0.6} />
    );
  }
  for (let y = 0; y <= heightFt; y += GRID_SPACING_FT) {
    const major = y % 10 === 0;
    gridLines.push(
      <line key={`h${y}`} x1={0} y1={ftToPx(y)} x2={svgWidth} y2={ftToPx(y)}
        stroke={isSat ? 'rgba(255,255,255,0.25)' : '#d1d5db'}
        strokeWidth={major ? 1 : 0.4}
        strokeOpacity={isSat ? (major ? 0.5 : 0.25) : 0.6} />
    );
  }

  // ── Off-screen building edge indicators ─────────────────────────────────────
  const edgeIndicators = buildingInfo.filter(b => !b.inView).map((b, i) => {
    const margin = 24;
    const cx = Math.max(margin, Math.min(svgWidth - margin, ftToPx(b.xFt)));
    const cy = Math.max(margin, Math.min(svgHeight - margin, ftToPx(b.yFt)));
    const aLen = 10;
    const ax = Math.cos(b.angle) * aLen;
    const ay = Math.sin(b.angle) * aLen;
    return (
      <g key={`bedge-${i}`} transform={`translate(${cx},${cy})`}>
        <polygon
          points={`${ax},${ay} ${-ay * 0.4 + ax * 0.3},${ax * 0.4 + ay * 0.3} ${ay * 0.4 + ax * 0.3},${-ax * 0.4 + ay * 0.3}`}
          fill="#64748b" fillOpacity={0.7} />
        <text x={0} y={-10} textAnchor="middle" fontSize="7" fontWeight="600"
          fill={isSat ? 'white' : '#475569'}
          stroke={isSat ? 'rgba(0,0,0,0.5)' : 'white'} strokeWidth="2" paintOrder="stroke">
          {Math.round(b.heightMeters * 3.28084)}ft
        </text>
      </g>
    );
  });

  // ── Sun compass geometry ────────────────────────────────────────────────────
  const compassR = 28;
  const compassCx = svgWidth - 32;
  const compassCy = 72; // below north arrow area

  // Sun path arc as SVG path string
  const sunArcD = sunPathPoints.length > 1
    ? sunPathPoints.map((p, i) => {
        const { x, y } = bearingToXY(p.azDeg, compassR - 5);
        return `${i === 0 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}`;
      }).join(' ')
    : null;

  // Current sun dot position
  const sunDot = sunAltDeg > 0 ? bearingToXY(sunAzDeg, compassR - 5) : null;

  // Label text color
  const labelFill = isSat ? 'white' : '#9ca3af';
  const labelStroke = isSat ? 'rgba(0,0,0,0.5)' : 'none';
  const labelStrokeW = isSat ? '2' : '0';

  return (
    <div className="border border-stone-300 rounded-xl overflow-hidden bg-white shadow-sm" style={{ maxWidth: '100%', overflowX: 'auto' }}>
      {/* Dimension labels */}
      <div className="flex items-center justify-between px-3 py-1.5 bg-stone-50 border-b border-stone-200 text-xs text-muted font-medium">
        <span>{widthFt} ft wide × {heightFt} ft deep</span>
        {shadowsOn && shadowPolygons.length > 0 && (
          <span className="flex items-center gap-1.5">
            <span className="inline-block w-3 h-3 rounded-sm bg-slate-800 opacity-50" />
            Shadows at {formatHour(shadowHour)}
          </span>
        )}
        <span className="flex items-center gap-1.5">
          <span className="inline-block w-2 h-2 rounded-full bg-primary opacity-60" /> Plants
          {nearbyBuildings.length > 0 && (
            <><span className="text-stone-300 mx-0.5">|</span>
            <span className="inline-block w-2 h-2 rounded-sm bg-slate-500 opacity-60" /> {nearbyBuildings.length} buildings</>
          )}
        </span>
      </div>

      <svg
        ref={svgRef}
        viewBox={`0 0 ${svgWidth} ${svgHeight}`}
        className="w-full"
        style={{
          maxHeight: '560px',
          cursor: editable ? (editTool === 'path' ? 'crosshair' : editTool === 'tree' ? 'pointer' : 'default') : 'default',
        }}
        onMouseDown={handleMouseDown}
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onClick={() => setPopupPlant(null)}
        onMouseLeave={() => { if (drawing) handleMouseUp(); }}
      >
        <defs>
          <pattern id="soil" x="0" y="0" width="4" height="4" patternUnits="userSpaceOnUse">
            <rect width="4" height="4" fill="#ecfdf5" />
            <circle cx="1" cy="1" r="0.5" fill="#d1fae5" />
            <circle cx="3" cy="3" r="0.5" fill="#d1fae5" />
          </pattern>
        </defs>

        {/* Background: satellite image or soil texture */}
        {satelliteUrl ? (
          <image href={satelliteUrl} x={0} y={0} width={svgWidth} height={svgHeight}
            preserveAspectRatio="xMidYMid slice" />
        ) : (
          <>
            <rect width={svgWidth} height={svgHeight} fill="#eef2f6" />
            <rect x={padPx} y={padPx} width={widthFt * PX_PER_FT} height={heightFt * PX_PER_FT} fill="#f8fafc" />
            <rect x={padPx} y={padPx} width={widthFt * PX_PER_FT} height={heightFt * PX_PER_FT} fill="url(#soil)" opacity={0.4} />
          </>
        )}

        {/* Garden border */}
        <rect x={padPx} y={padPx} width={widthFt * PX_PER_FT} height={heightFt * PX_PER_FT}
          fill="none" stroke={isSat ? 'rgba(255,255,255,0.5)' : '#a8b5c4'} strokeWidth={1.5}
          strokeDasharray={isSat ? '6,3' : 'none'} rx={2} />

        {/* Grid lines */}
        {gridLines}

        {/* Ft labels every 5 ft */}
        {Array.from({ length: Math.floor(widthFt / 5) + 1 }).map((_, i) => (
          <text key={`xl${i}`} x={ftToPx(i * 5)} y={svgHeight - 3} fontSize="9"
            fill={labelFill} textAnchor="middle"
            stroke={labelStroke} strokeWidth={labelStrokeW} paintOrder="stroke">
            {i * 5}&apos;
          </text>
        ))}
        {Array.from({ length: Math.floor(heightFt / 5) + 1 }).map((_, i) => (
          <text key={`yl${i}`} x={3} y={ftToPx(i * 5)} fontSize="9"
            fill={labelFill} dominantBaseline="middle"
            stroke={labelStroke} strokeWidth={labelStrokeW} paintOrder="stroke">
            {i * 5}&apos;
          </text>
        ))}

        {/* Species zone washes (hidden when satellite is on — they obscure imagery) */}
        {!isSat && Array.from(speciesGroups.values()).map((zone, i) => (
          <ellipse key={`zone-${i}`}
            cx={ftToPx(zone.cx)} cy={ftToPx(zone.cy)}
            rx={ftToSize(zone.r)} ry={ftToSize(zone.r * 0.75)}
            fill={zone.color} fillOpacity={0.08} />
        ))}

        {/* Building footprints (visible buildings near/in viewport) */}
        {buildingInfo.filter(b => b.inView).map((b, i) => {
          const halfPx = ftToSize(b.wFt / 2);
          const cx = ftToPx(b.xFt);
          const cy = ftToPx(b.yFt);
          return (
            <g key={`bldg-${i}`}>
              <rect x={cx - halfPx} y={cy - halfPx} width={halfPx * 2} height={halfPx * 2}
                fill={isSat ? 'rgba(100,116,139,0.25)' : '#94a3b8'}
                fillOpacity={isSat ? 0.25 : 0.2}
                stroke={isSat ? 'rgba(255,255,255,0.6)' : '#64748b'}
                strokeWidth={1.5} strokeDasharray="4,2" rx={2} />
              <text x={cx} y={cy} textAnchor="middle" dominantBaseline="central"
                fontSize="9" fontWeight="700"
                fill={isSat ? 'white' : '#475569'}
                stroke={isSat ? 'rgba(0,0,0,0.6)' : 'white'} strokeWidth="2.5" paintOrder="stroke">
                {Math.round(b.heightMeters * 3.28084)}ft
              </text>
            </g>
          );
        })}

        {/* Shadow overlay */}
        {shadowPolygons.map((pts, i) => (
          <polygon key={`shadow-${i}`} points={pts}
            fill="#0f172a" fillOpacity={isSat ? 0.5 : 0.38}
            stroke="#0f172a" strokeWidth={0.3} strokeOpacity={0.2} />
        ))}

        {/* Off-screen building direction indicators */}
        {edgeIndicators}

        {/* Exclusion zones */}
        {exclusionZones.map(z => {
          const rect = (z as any).gridRect;
          if (!rect) return null;
          return (
            <g key={z.id}
              onClick={() => editable && editTool === 'select' && onFeatureRemoved?.('zone', z.id)}
              style={{ cursor: editable && editTool === 'select' ? 'pointer' : 'default' }}>
              <rect x={ftToPx(rect.xFt)} y={ftToPx(rect.yFt)} width={ftToSize(rect.wFt)} height={ftToSize(rect.hFt)}
                fill={isSat ? 'rgba(100,116,139,0.4)' : '#6b7280'} fillOpacity={isSat ? 0.4 : 0.2}
                stroke={isSat ? 'rgba(255,255,255,0.7)' : '#9ca3af'} strokeWidth={1.5} strokeDasharray="6,3" rx={3} />
              <text x={ftToPx(rect.xFt + rect.wFt / 2)} y={ftToPx(rect.yFt + rect.hFt / 2)}
                textAnchor="middle" dominantBaseline="middle" fontSize="10"
                fill={isSat ? 'white' : '#374151'} fontWeight="500"
                stroke={isSat ? 'rgba(0,0,0,0.5)' : 'none'} strokeWidth={isSat ? '2' : '0'} paintOrder="stroke">
                {z.label}
              </text>
            </g>
          );
        })}

        {/* Existing trees */}
        {existingTrees.map(t => {
          const xFt = (t as any).gridXFt ?? latLngToFt(t.lat, t.lng).xFt;
          const yFt = (t as any).gridYFt ?? latLngToFt(t.lat, t.lng).yFt;
          const rPx = ftToSize(t.canopyDiameterFt / 2);
          return (
            <g key={t.id}
              onClick={() => editable && editTool === 'select' && onFeatureRemoved?.('tree', t.id)}
              style={{ cursor: editable && editTool === 'select' ? 'pointer' : 'default' }}>
              <circle cx={ftToPx(xFt)} cy={ftToPx(yFt)} r={rPx}
                fill="#15803d" fillOpacity={0.15} stroke={isSat ? 'rgba(255,255,255,0.6)' : '#15803d'}
                strokeWidth={1.5} strokeDasharray="4,2" strokeOpacity={0.5} />
              <circle cx={ftToPx(xFt)} cy={ftToPx(yFt)} r={4} fill="#713f12" stroke="white" strokeWidth={1.5} />
              <text x={ftToPx(xFt)} y={ftToPx(yFt) - rPx - 5}
                textAnchor="middle" fontSize="9" fontWeight="600"
                fill={isSat ? 'white' : '#14532d'}
                stroke={isSat ? 'rgba(0,0,0,0.5)' : 'white'} strokeWidth="2" paintOrder="stroke">
                {t.label} ({t.canopyDiameterFt}ft)
              </text>
            </g>
          );
        })}

        {/* Plant placements — render style picked by `renderStyle` prop.
         *  All three branches share the same click → popup behavior so the
         *  on-screen interactivity is identical regardless of style. */}
        {plantsWithCoords.map((p, i) => {
          const { xFt, yFt } = latLngToFt(p.lat!, p.lng!);
          if (xFt < -1 || xFt > widthFt + 1 || yFt < -1 || yFt > heightFt + 1) return null;

          const spreadFt = (p.spreadInches || 24) / 12;
          const radiusPx = Math.min(11, Math.max(5, spreadFt * PX_PER_FT * 0.22));
          const color = getPlantColor(p.bloomColor);
          const isSelected = selectedSlug === p.plantSlug;
          const cx = ftToPx(xFt), cy = ftToPx(yFt);
          const onClick = (e: React.MouseEvent) => {
            e.stopPropagation();
            onPlantClick?.(p.plantSlug);
            setPopupPlant(popupPlant?.plant.plantSlug === p.plantSlug && popupPlant?.cx === cx ? null : { plant: p, cx, cy });
          };

          // ── Tapestry: filled Voronoi cell from cellGeoJson, abbrev label.
          //    Falls back to dots when no cell is available.
          if (renderStyle === 'tapestry' && p.cellGeoJson?.coordinates?.[0]?.length) {
            const cellPts = p.cellGeoJson.coordinates[0]
              .map(([lng, lat]) => latLngToFt(lat, lng))
              .map(({ xFt, yFt }) => `${ftToPx(xFt)},${ftToPx(yFt)}`)
              .join(' ');
            const fill = tapestryColor(p.speciesIndex || 0, p.plantSlug);
            const abbrev = speciesAbbrev(p.plantSlug, p.commonName);
            return (
              <g key={`${p.plantSlug}-${i}`} onClick={onClick} style={{ cursor: 'pointer' }}>
                <polygon points={cellPts}
                  fill={fill} fillOpacity={isSelected ? 0.95 : 0.78}
                  stroke="white" strokeWidth={0.8} strokeOpacity={0.9} />
                <text x={cx} y={cy} textAnchor="middle" dominantBaseline="central"
                  fontSize="7" fontWeight="bold" fill="white"
                  stroke="rgba(0,0,0,0.55)" strokeWidth="1.6" paintOrder="stroke">
                  {abbrev}
                </text>
              </g>
            );
          }

          // ── Matrix: square cell sized to plant spread. Reads like a
          //    planting matrix — every plant occupies a clearly-bounded square
          //    you can tape-measure on site.
          if (renderStyle === 'matrix') {
            const cellPx = Math.max(10, Math.min(28, spreadFt * PX_PER_FT * 0.5));
            const half = cellPx / 2;
            return (
              <g key={`${p.plantSlug}-${i}`} onClick={onClick} style={{ cursor: 'pointer' }}>
                {isSelected && <rect x={cx - half - 2} y={cy - half - 2} width={cellPx + 4} height={cellPx + 4}
                  fill="none" stroke="#000" strokeWidth={2} strokeOpacity={0.5} rx={2} />}
                <rect x={cx - half} y={cy - half} width={cellPx} height={cellPx}
                  fill={color} fillOpacity={0.85}
                  stroke="white" strokeWidth={1} rx={2} />
                {p.speciesIndex != null && (
                  <text x={cx} y={cy} textAnchor="middle" dominantBaseline="central"
                    fontSize={cellPx >= 18 ? '9' : '7'} fontWeight="bold" fill="white"
                    stroke="rgba(0,0,0,0.55)" strokeWidth="1.6" paintOrder="stroke">
                    {p.speciesIndex}
                  </text>
                )}
              </g>
            );
          }

          // ── Dots (default / tapestry-fallback): the historical look.
          return (
            <g key={`${p.plantSlug}-${i}`} onClick={onClick} style={{ cursor: 'pointer' }}>
              {isSelected && <circle cx={cx} cy={cy} r={radiusPx + 3} fill="none" stroke="#000" strokeWidth={2} strokeOpacity={0.5} />}
              {/* Wider backing disc on satellite for contrast */}
              <circle cx={cx} cy={cy} r={radiusPx + (isSat ? 2 : 1)}
                fill={isSat ? 'rgba(0,0,0,0.5)' : 'white'} fillOpacity={isSat ? 0.5 : 0.6} />
              <circle cx={cx} cy={cy} r={radiusPx}
                fill={color} fillOpacity={0.88}
                stroke="white" strokeWidth={isSat ? 1.5 : 1} />
              {p.speciesIndex != null && (
                <text x={cx} y={cy} textAnchor="middle" dominantBaseline="central"
                  fontSize={radiusPx >= 9 ? '8' : '7'} fontWeight="bold" fill="white"
                  stroke="rgba(0,0,0,0.55)" strokeWidth="1.8" paintOrder="stroke">
                  {p.speciesIndex}
                </text>
              )}
            </g>
          );
        })}

        {/* Plant info popup */}
        {popupPlant && (() => {
          const pp = popupPlant;
          const pw = 160, ph = 52;
          // Position above the plant, flip down if too close to top
          const flipDown = pp.cy - ph - 12 < 0;
          const px = Math.max(4, Math.min(svgWidth - pw - 4, pp.cx - pw / 2));
          const py = flipDown ? pp.cy + 16 : pp.cy - ph - 12;
          return (
            <g onClick={(e) => { e.stopPropagation(); setPopupPlant(null); }} style={{ cursor: 'pointer' }}>
              <rect x={px} y={py} width={pw} height={ph} rx={6}
                fill="white" stroke="#d1d5db" strokeWidth={1} filter="drop-shadow(0 2px 4px rgba(0,0,0,0.15))" />
              <rect x={px + 4} y={py + 6} width={10} height={10} rx={5}
                fill={getPlantColor(pp.plant.bloomColor)} />
              <text x={px + 18} y={py + 14} fontSize="9" fontWeight="700" fill="#1e293b" dominantBaseline="central">
                {pp.plant.commonName.length > 20 ? pp.plant.commonName.slice(0, 19) + '…' : pp.plant.commonName}
              </text>
              <text x={px + 6} y={py + 28} fontSize="7.5" fill="#64748b" fontStyle="italic" dominantBaseline="central">
                {pp.plant.scientificName?.length > 24 ? pp.plant.scientificName.slice(0, 23) + '…' : pp.plant.scientificName}
              </text>
              <text x={px + 6} y={py + 42} fontSize="7.5" fill="#475569" dominantBaseline="central">
                {pp.plant.bloomColor} · {pp.plant.heightMaxInches ? `${Math.round(pp.plant.heightMaxInches / 12)}ft` : ''} · #{pp.plant.speciesIndex}
              </text>
            </g>
          );
        })()}

        {/* Sun compass — combined north arrow + sun path */}
        <g transform={`translate(${compassCx}, ${compassCy})`}>
          <circle r={compassR} fill="rgba(15,23,42,0.6)" />
          <circle r={compassR} fill="none" stroke="rgba(255,255,255,0.15)" strokeWidth={0.5} />

          {/* Sun path arc */}
          {sunArcD && (
            <path d={sunArcD} fill="none" stroke="#fbbf24" strokeWidth={2.5}
              strokeOpacity={0.5} strokeLinecap="round" />
          )}

          {/* Current sun position */}
          {sunDot && (
            <>
              <circle cx={sunDot.x} cy={sunDot.y} r={5} fill="#fbbf24" stroke="white" strokeWidth={1} />
              <circle cx={sunDot.x} cy={sunDot.y} r={2} fill="#f59e0b" />
            </>
          )}

          {/* North indicator */}
          <polygon points="0,-22 3,-14 -3,-14" fill="white" fillOpacity={0.9} />
          <text x={0} y={-13} textAnchor="middle" fontSize="6" fill="white" fontWeight="bold" dominantBaseline="central">N</text>

          {/* Cardinal directions */}
          <text x={0} y={20} textAnchor="middle" fontSize="5" fill="rgba(255,255,255,0.5)">S</text>
          <text x={20} y={1} textAnchor="middle" fontSize="5" fill="rgba(255,255,255,0.5)" dominantBaseline="central">E</text>
          <text x={-20} y={1} textAnchor="middle" fontSize="5" fill="rgba(255,255,255,0.5)" dominantBaseline="central">W</text>
        </g>

        {/* Sun compass label */}
        <text x={compassCx} y={compassCy + compassR + 10} textAnchor="middle" fontSize="7"
          fill={isSat ? 'white' : '#6b7280'}
          stroke={isSat ? 'rgba(0,0,0,0.5)' : 'none'} strokeWidth={isSat ? '2' : '0'}
          paintOrder="stroke">
          {formatHour(shadowHour)}
        </text>

        {/* Drawing preview */}
        {editable && drawing && drawStart && drawCurrent && editTool === 'path' && (
          <rect
            x={Math.min(drawStart.x, drawCurrent.x)}
            y={Math.min(drawStart.y, drawCurrent.y)}
            width={Math.abs(drawCurrent.x - drawStart.x)}
            height={Math.abs(drawCurrent.y - drawStart.y)}
            fill={isSat ? 'rgba(100,116,139,0.3)' : '#9ca3af'}
            fillOpacity={isSat ? 0.3 : 0.2}
            stroke={isSat ? 'rgba(255,255,255,0.7)' : '#6b7280'}
            strokeWidth={2} strokeDasharray="8,4" rx={4}
          />
        )}

        {/* Scale bar — bottom right */}
        <g transform={`translate(${svgWidth - 80}, ${svgHeight - 14})`}>
          <rect x={0} y={4} width={ftToSize(5)} height={4}
            fill={isSat ? 'white' : '#374151'} rx={1} />
          <text x={0} y={2} fontSize="8" fill={isSat ? 'white' : '#6b7280'}
            stroke={isSat ? 'rgba(0,0,0,0.4)' : 'none'} strokeWidth={isSat ? '2' : '0'} paintOrder="stroke">0</text>
          <text x={ftToSize(5)} y={2} fontSize="8" fill={isSat ? 'white' : '#6b7280'} textAnchor="middle"
            stroke={isSat ? 'rgba(0,0,0,0.4)' : 'none'} strokeWidth={isSat ? '2' : '0'} paintOrder="stroke">5 ft</text>
        </g>
      </svg>

      {/* Label input for drawn path */}
      {editable && pendingPath && (
        <div className="flex items-center gap-2 px-3 py-2 bg-stone-50 border-t border-stone-200">
          <input
            type="text"
            value={pathLabel}
            onChange={e => setPathLabel(e.target.value)}
            placeholder="Label (e.g. Sidewalk, Patio)"
            className="flex-1 px-3 py-1.5 border border-stone-300 rounded-lg text-sm outline-none focus:border-primary"
            autoFocus
            onKeyDown={e => e.key === 'Enter' && confirmPath()}
          />
          <button onClick={confirmPath} className="px-4 py-1.5 bg-primary text-white rounded-lg text-sm font-medium">
            Add
          </button>
          <button onClick={() => { setPendingPath(null); setPathLabel(''); }}
            className="px-3 py-1.5 border border-stone-300 rounded-lg text-sm">
            Cancel
          </button>
        </div>
      )}
    </div>
  );
}
